### ISSUE TITLE
Lab2 Review

### ISSUE THREAD

**Issue by Punctuality** [Avvessalom/itmo-functional-programming#1]

**Comment by Punctuality** [comment]
Тут просто заглушка и ничего не вызывается https://github.com/Avvessalom/itmo-functional-programming/blob/b421e1c662a652c2565953a98a549367274add4c/src/itmo_functional_programming/lab2/main.clj#L4

**Comment by Punctuality** [comment]
Я так понимаю ты хотел дергать вот это дело 
https://github.com/Avvessalom/itmo-functional-programming/blob/b421e1c662a652c2565953a98a549367274add4c/src/itmo_functional_programming/lab2/hash_set.clj#L51

**Comment by Punctuality** [comment]
Я делал тоже самое, тут в данном случае не используется а товарищ может по копирайту заподозрить :) https://github.com/Avvessalom/itmo-functional-programming/blob/b421e1c662a652c2565953a98a549367274add4c/src/itmo_functional_programming/lab2/hash_set.clj#L8

**Comment by Punctuality** [comment]
Можно просто использовать `{}`, да это будет по стандарту создавать ArrayMap, ну и пофег. У тебя все равно иммутабельно все https://github.com/Avvessalom/itmo-functional-programming/blob/b421e1c662a652c2565953a98a549367274add4c/src/itmo_functional_programming/lab2/hash_set.clj#L16

**Comment by Punctuality** [comment]
Хотя это конечно имхо. Просто необязательно сразу же создавать полноценную hash-map'у со всеми бакетами

**Comment by Punctuality** [comment]
Могу ошибаться, но не обязательно хоть что-то хранить в этой мапе. https://github.com/Avvessalom/itmo-functional-programming/blob/b421e1c662a652c2565953a98a549367274add4c/src/itmo_functional_programming/lab2/hash_set.clj#L15

Жрет место и дополнительные ссылки

Есть два пути наверное:
1. Просто забить и хранить value = nil
2. Посмотреть как внутри работает и сделать кастомный IMapEntry (но тогда скорее всего надо писать собственную хэш мапу 😄)

**Comment by Avvessalom** [comment]
> Есть два пути наверное:
> 
> 1. Просто забить и хранить value = nil
> 2. Посмотреть как внутри работает и сделать кастомный IMapEntry (но тогда скорее всего надо писать собственную хэш мапу smile)

Так работает в настоящей))00)) Прям пары ключ = значение

**Comment by Punctuality** [comment]
Вот тут вложенные if'ы https://github.com/Avvessalom/itmo-functional-programming/blob/b421e1c662a652c2565953a98a549367274add4c/src/itmo_functional_programming/lab2/hash_set.clj#L17

Можно просто было взять `or` внутри одного ифа

**Comment by Punctuality** [comment]
Да строчка и вправду убийственная :) https://github.com/Avvessalom/itmo-functional-programming/blob/b421e1c662a652c2565953a98a549367274add4c/src/itmo_functional_programming/lab2/hash_set.clj#L21

Но по-моему легче как-то так
```clojure
(every? #(contains? {1 nil 2 nil 3 nil} %)  [1 2 3])
```

(Можно и без contains, но тогда каждое value, должно быть не nil)

А еще это тупо будет быстрее работать 😄

**Comment by Punctuality** [comment]
Не смог это завести без `print-method`?
https://github.com/Avvessalom/itmo-functional-programming/blob/b421e1c662a652c2565953a98a549367274add4c/src/itmo_functional_programming/lab2/hash_set.clj#L41

**Comment by Avvessalom** [comment]
> Не смог это завести без `print-method`?
> 
> https://github.com/Avvessalom/itmo-functional-programming/blob/b421e1c662a652c2565953a98a549367274add4c/src/itmo_functional_programming/lab2/hash_set.clj#L41

и с ним не смог. У меня выводит #{(1 2 3)}

**Comment by Punctuality** [comment]
Вот тут мне кажется не до конца правильно. 

https://github.com/Avvessalom/itmo-functional-programming/blob/b421e1c662a652c2565953a98a549367274add4c/test/itmo_functional_programming/lab2/hash_set_property_based_tests.clj#L1

У тебя тут конечно правила гораздо больше и круче. Но в property-based testing есть тема в том что там должны быть сгенерированные данные и прогоняются тесты несколько раз. Можешь посмотреть как у меня это сделано. 

У меня кстати это сделано по тупому, но как бы концепт сохранен. Есть вариант посмотреть прямо библиотеки для pb-testing'a, которые еще и автоматически минимизируют выборку данных на лету. Это прямо то что товарищ советует 🤷
